package com.dynns.cloudtecnologia.certificados.model.enums;

public enum TipoLog {
    USER_CERTIFICADO_INSTALADO,
    ADMIN_CERTIFICADO_DELETADO,
    ADMIN_CERTIFICADO_ENVIADO_EMAIL,
    ADMIN_ALTERACAO_PREFERENCIAS,
    ADMIN_DELETAR_CERTIFICADOS_VENCIDOS,
    ADMIN_ATUALIZAR_CERTIFICADOS
}
