/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.instalador.view.TELAS;

import br.com.instalador.controle.CERTIFICADOS_PASTA;
import br.com.instalador.controle.TelaController;
import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author Thiago
 */
public final class TelaEditarPreferencias extends javax.swing.JFrame {

    //
    public TelaController controle;

    //
    /**
     * Creates new form EDITAR_PREFERENCIAS
     */
    public TelaEditarPreferencias() {
        initComponents();
        mostra();
    }

    public void mostra() {
        this.setLocationRelativeTo(null);
        this.setVisible(true);
        this.setEnabled(true);
    }

    public void atualizaTela() {

        C_PASTA.setText(controle.retornarCaminhoDaPasta());
        C_SENHA_CERT.setText(controle.retornarSenhaCertificado());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        C_PASTA = new javax.swing.JTextField();
        C_SENHA_CERT = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        BT_SALVAR = new javax.swing.JButton();
        BT_EDIT = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        BT_UPDADE_CERTS = new javax.swing.JButton();
        BT_DELETA_VENCIDOS = new javax.swing.JButton();
        BT_DELETA_DUPLICADOS = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "EDITAR PREFERÊNCIAS", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        C_PASTA.setEditable(false);
        C_PASTA.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        C_PASTA.setEnabled(false);

        C_SENHA_CERT.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        C_SENHA_CERT.setEnabled(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("PASTA CERTIFICADOS");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("SENHA CERTIFICADOS");

        BT_SALVAR.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BT_SALVAR.setText("SALVAR");
        BT_SALVAR.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        BT_SALVAR.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BT_SALVAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT_SALVARActionPerformed(evt);
            }
        });

        BT_EDIT.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BT_EDIT.setText("EDITAR");
        BT_EDIT.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        BT_EDIT.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BT_EDIT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT_EDITActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 402, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/instalador/view/TELAS/lupa.png"))); // NOI18N
        jButton1.setText(" ");
        jButton1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        BT_UPDADE_CERTS.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BT_UPDADE_CERTS.setText("ATUALIZAR CERTIFICADOS BD");
        BT_UPDADE_CERTS.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        BT_UPDADE_CERTS.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BT_UPDADE_CERTS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT_UPDADE_CERTSActionPerformed(evt);
            }
        });

        BT_DELETA_VENCIDOS.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BT_DELETA_VENCIDOS.setText("DELETAR VENCIDOS");
        BT_DELETA_VENCIDOS.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        BT_DELETA_VENCIDOS.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BT_DELETA_VENCIDOS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT_DELETA_VENCIDOSActionPerformed(evt);
            }
        });

        BT_DELETA_DUPLICADOS.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BT_DELETA_DUPLICADOS.setText("DELETAR DUPLICADOS");
        BT_DELETA_DUPLICADOS.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        BT_DELETA_DUPLICADOS.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BT_DELETA_DUPLICADOS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT_DELETA_DUPLICADOSActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(C_PASTA, javax.swing.GroupLayout.PREFERRED_SIZE, 531, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(C_SENHA_CERT))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(BT_EDIT, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BT_SALVAR, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BT_DELETA_VENCIDOS, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BT_DELETA_DUPLICADOS, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BT_UPDADE_CERTS, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(31, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(333, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(C_PASTA, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(C_SENHA_CERT, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BT_EDIT, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BT_SALVAR, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BT_UPDADE_CERTS, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BT_DELETA_VENCIDOS, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BT_DELETA_DUPLICADOS, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(124, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(27, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BT_EDITActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT_EDITActionPerformed
        if (C_PASTA.isEnabled() && C_SENHA_CERT.isEnabled()) {
            C_PASTA.setEnabled(false);
            C_SENHA_CERT.setEnabled(false);
            C_PASTA.setEditable(false);
            C_SENHA_CERT.setEditable(false);
        } else {
            C_PASTA.setEnabled(true);
            C_SENHA_CERT.setEnabled(true);
            C_PASTA.setEditable(true);
            C_SENHA_CERT.setEditable(true);
        }
    }//GEN-LAST:event_BT_EDITActionPerformed

    private void BT_SALVARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT_SALVARActionPerformed
        //
        C_PASTA.setEnabled(false);
        C_SENHA_CERT.setEnabled(false);
        C_PASTA.setEditable(false);
        C_SENHA_CERT.setEditable(false);
        //      
        controle.atualizarPreferencias(C_PASTA.getText().trim(), C_SENHA_CERT.getText().trim());
        JOptionPane.showMessageDialog(null, "Preferências Atualizadas!");

        atualizaTela();
    }//GEN-LAST:event_BT_SALVARActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        JFileChooser fc1 = new JFileChooser();
        fc1.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        int res1 = fc1.showOpenDialog(null);
        if (res1 == JFileChooser.APPROVE_OPTION) {
            File diretorio1 = fc1.getSelectedFile();
            File url1 = new File(diretorio1.getPath());
            if (url1.exists()) {
                C_PASTA.setText(url1.getAbsolutePath());
            } else {
                JOptionPane.showMessageDialog(null, "SELECIONE A PASTA QUE CONTÉM OS CERTIFICADOS!");
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void BT_UPDADE_CERTSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT_UPDADE_CERTSActionPerformed

        int response = JOptionPane.showConfirmDialog(null, "DESEJA PROCESSAR OS CERTIFICADOS DA PASTA "
                + "(" + C_PASTA.getText() + ")? ", "Confirma?",
                JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (response == JOptionPane.NO_OPTION) {
            JOptionPane.showMessageDialog(null, "CANCELADO!");
        } else {
            if (response == JOptionPane.YES_NO_OPTION) {
                BT_UPDADE_CERTS.setEnabled(false);
                BT_EDIT.setEnabled(false);
                BT_SALVAR.setEnabled(false);
                BT_DELETA_VENCIDOS.setEnabled(false);
                //
                ProcessoATUALIZA_CERTS procUpdateCerts = new ProcessoATUALIZA_CERTS();
                Thread threadUpdatCerts = new Thread(procUpdateCerts);
                threadUpdatCerts.setName("Thread threadUpdatCerts");
                threadUpdatCerts.start();
            }
        }
    }//GEN-LAST:event_BT_UPDADE_CERTSActionPerformed

    private void BT_DELETA_VENCIDOSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT_DELETA_VENCIDOSActionPerformed
        int response = JOptionPane.showConfirmDialog(null, "DESEJA DELETAR TODOS OS CERTIFICADOS VENCIDOS? ", "Confirma?",
                JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (response == JOptionPane.NO_OPTION) {
            JOptionPane.showMessageDialog(null, "EXCLUSÃO CANCELADA!");
        } else {
            if (response == JOptionPane.YES_NO_OPTION) {

                if (controle.deletarCertificadosVencidos()) {
                    JOptionPane.showMessageDialog(null, "OS CERTIFICADOS VENCIDOS FORAM EXCLUÍDOS!");
                }
            }
        }
    }//GEN-LAST:event_BT_DELETA_VENCIDOSActionPerformed

    private void BT_DELETA_DUPLICADOSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT_DELETA_DUPLICADOSActionPerformed
        int response = JOptionPane.showConfirmDialog(null, "DESEJA DELETAR TODOS OS CERTIFICADOS DUPLICADOS? ", "Confirma?",
                JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (response == JOptionPane.NO_OPTION) {
            JOptionPane.showMessageDialog(null, "EXCLUSÃO CANCELADA!");
        } else {
            if (response == JOptionPane.YES_NO_OPTION) {

                if (controle.deletarCertificadosDuplicados()) {
                    JOptionPane.showMessageDialog(null, "OS CERTIFICADOS DUPLICADOS FORAM EXCLUÍDOS!");
                }
            }
        }
    }//GEN-LAST:event_BT_DELETA_DUPLICADOSActionPerformed

    public class ProcessoATUALIZA_CERTS implements Runnable {

        @Override
        public void run() {
            File caminho = new File(C_PASTA.getText().trim());
            if (caminho.exists() & caminho.isDirectory()) {
                CERTIFICADOS_PASTA updateCertsBD = new CERTIFICADOS_PASTA();
                updateCertsBD.atualizarCertificadosBD(C_PASTA.getText().trim(),
                        C_SENHA_CERT.getText().trim(), controle);
            } else {
                JOptionPane.showMessageDialog(null, "A PASTA INFORMADA É INVÁLIDA OU ESSE COMPUTADOR"
                        + " NÃO POSSUI ACESSO À ELA!");
                BT_UPDADE_CERTS.setEnabled(true);
                BT_EDIT.setEnabled(true);
                BT_SALVAR.setEnabled(true);
            }
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaEditarPreferencias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaEditarPreferencias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaEditarPreferencias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaEditarPreferencias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaEditarPreferencias().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BT_DELETA_DUPLICADOS;
    private javax.swing.JButton BT_DELETA_VENCIDOS;
    private javax.swing.JButton BT_EDIT;
    private javax.swing.JButton BT_SALVAR;
    private javax.swing.JButton BT_UPDADE_CERTS;
    private javax.swing.JTextField C_PASTA;
    private javax.swing.JTextField C_SENHA_CERT;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables

    /**
     * @param controle the controle to set
     */
    public void setControle(TelaController controle) {
        this.controle = controle;
    }

}
